name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
    - name: Print Hash
      id: hash
      run: |
        echo ${{ env.COMMIT_SHORT_SHA }}
        ls -al
    - name: Build the Docker image
      run: |
        cd YSFReflector/docker
        docker build . --file Dockerfile --tag nq0m/ysfreflector:$(date +%Y%m%d)-${{ env.COMMIT_SHORT_SHA }}
