name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build the Docker image
      run: |
        cd YSFReflector/docker
        docker build . --file Dockerfile --tag nq0m/ysfreflector:latest
        docker tag nq0m/ysfreflector:latest nq0m/ysfreflector:$(date +%Y%m%d)-${{ env.COMMIT_SHORT_SHA }}
    - name: Push the Docker image to Docker Hub
      run: |
        docker push nq0m/ysfreflector:latest
        docker push nq0m/ysfreflector:$(date +%Y%m%d)-${{ env.COMMIT_SHORT_SHA }}
