name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: prompt/actions-commit-hash@v3
    - name: Print Hash
      id: hash
      run: echo ${{ steps.commit.outputs.short }}
    - name: Build the Docker image
      run: |
        cd $GITHUB_WORKSPACE/DVReflectors/YSFReflector/docker
        docker build . --file Dockerfile --tag nq0m/ysfreflector:$(date +%Y%m%d)-${{ steps.commit.outputs.short }}
